---
driver:
  name: dokken

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  # @see https://github.com/someara/dokken-images
  # @see https://hub.docker.com/r/dokken/
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
  - name: centos-6
    driver:
      image: dokken/centos-6
  - name: centos-7
    driver:
      image: dokken/centos-7
  - name: debian-10
    driver:
      image: dokken/debian-10

suites:
  - name: default
    run_list:
      - recipe[ssl_cacert_hack::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
